version: "3"
services: 
    app:
        build: .
        image: gt-app
        container_name: gt-app
        depends_on:
            - database
            - redis
        ports:
            - "8080:8080"
        links:
            - database:database
            - redis:redis
        volumes:
            - ./storage:/srv/app/storage
    database:
        container_name: gt-db
        image: mysql:5.7
        ports:
            - "13309:3306"
        volumes:
            - .docker/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=gene_tracker
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=gene_tracker
            - MYSQL_USER=password
    redis:
        image: centos/redis-5-centos7
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=beans
    artisan:
        image: gt-app
        container_name: gt-artisan
        entrypoint: [
            "php",
            "/srv/app/artisan"
        ]
    