kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: clean-backups
  namespace: dept-gpm
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: db-backup
        spec:
          containers:
            - name: backup-cleaner
              image: 'image-registry.openshift-image-registry.svc:5000/openshift/cron'
              args:
                - cron
                - for x in $(find ${BACKUP_PATH} -type f -mtime +14); do rm "$x"; done; echo 'Cleaned backups.' 
              env:
                - name: PROJECT
                  value: dept-gpm
                - name: DEPLOYMENT
                  value: os-mysql
                - name: OPENSHIFT_TOKEN
                  value: TOKEN
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
